### ISSUE TITLE
About avazu and criteo files

### ISSUE THREAD

**Issue by su-go** [qitianwu/FATE#3]
Hello, I downloaded the preprocessed avazu and criteo files according to the address you gave. How are these two files processed? The preprocessing.py file given seems to be incomplete.

**Comment by qitianwu** [comment]
Hi, the preprocessed pkl files are obtained by using the "data_preprocess" function in preprocessing.py which is a complete version uploaded

**Comment by su-go** [comment]
Thank you very much!
